### ISSUE TITLE
RHOSO deployment using OpenShift Gitops steps redirect to Connected Environment instructions

### ISSUE THREAD

**Issue by YoNoSoyVictor** [rh-osp-demo/showroom_osp-on-ocp#3]
Hey there!

It seems that the instructions at ```https://rh-osp-demo.github.io/showroom_osp-on-ocp/modules/prereqs.html``` are not working as intended for "RHOSO deployment using OpenShift Gitops". Clicking on the instructions there will redirect to the equivalent section on the Connected Environment section. 

Is this something you may be able to take a look at?

**Comment by pnavarro** [comment]
hey, I just submitted a patch to fix the Gitops doc:

https://rh-osp-demo.github.io/showroom_osp-on-ocp/modules/gitops.html
